-- 第十一轮对齐（可重复执行）
-- 执行顺序：... → gamescreen_fill.sql → 本脚本

-- 独立弹幕场景插件（默认关闭）
insert into gs_plug (activity_id, name, title, enabled, order_num, hotkey, is_module)
select 1, 'danmu', '弹幕墙', '2', 19, '', 2
where not exists (select 1 from gs_plug p where p.activity_id = 1 and p.name = 'danmu');

-- 游戏内定（目标名次）
create table if not exists gs_game_preset (
  id int8 generated by default as identity primary key,
  activity_id int8 not null default 1,
  attendee_id int8 not null,
  target_rank int4 not null default 1,
  theme varchar(64) default '',
  used char(1) default '0',
  create_time timestamp default now()
);
create index if not exists idx_gs_game_preset_act on gs_game_preset(activity_id);
