-- 未对齐功能补全（可重复执行）
-- 执行顺序：ry_postgresql.sql → gamescreen_pg.sql → gamescreen_align.sql → gamescreen_menu_fix.sql → 本脚本

alter table gs_activity add column if not exists qrcode_url varchar(512) default '';
alter table gs_activity add column if not exists h5_sign_bg_url varchar(512) default '';
alter table gs_activity add column if not exists h5_tab_color varchar(32) default '#1a5f4a';

create table if not exists gs_h5_menu (
  id int8 generated by default as identity primary key,
  activity_id int8 not null default 1,
  tab_key varchar(32) not null,
  title varchar(64) not null,
  icon varchar(128) default '',
  order_num int4 default 0,
  enabled char(1) default '0'
);

-- 默认 H5 底部菜单（活动 1）
insert into gs_h5_menu (activity_id, tab_key, title, order_num, enabled)
select 1, v.tab_key, v.title, v.ord, '0' from (values
  ('sign','签到',1),('wall','上墙',2),('vote','投票',3),('game','游戏',4),
  ('lottery','抽奖',5),('red','红包',6),('prizes','中奖',7),('more','更多',8)
) as v(tab_key, title, ord)
where not exists (select 1 from gs_h5_menu where activity_id = 1 and tab_key = v.tab_key);

-- 菜单 3048+（挂载活动大屏 3000）
insert into sys_menu values('3048', '数据导出', '3000', '14', 'export', 'gamescreen/export/index', '', '', 1, 0, 'C', '0', '0', 'gs:export:list', 'download', 'admin', now(), '', null, '签到/中奖/排行等导出')
on conflict (menu_id) do update set parent_id='3000', component=excluded.component, perms=excluded.perms;
insert into sys_menu values('3049', '导出执行', '3048', '1', '', '', '', '', 1, 0, 'F', '0', '0', 'gs:export:export', '#', 'admin', now(), '', null, '')
on conflict (menu_id) do nothing;
insert into sys_menu values('3050', 'H5菜单', '3000', '15', 'h5menu', 'gamescreen/h5menu/index', '', '', 1, 0, 'C', '0', '0', 'gs:h5menu:list', 'list', 'admin', now(), '', null, '手机端底部菜单')
on conflict (menu_id) do update set parent_id='3000', component=excluded.component, perms=excluded.perms;
insert into sys_menu values('3051', 'H5菜单修改', '3050', '1', '', '', '', '', 1, 0, 'F', '0', '0', 'gs:h5menu:edit', '#', 'admin', now(), '', null, '')
on conflict (menu_id) do nothing;
insert into sys_menu values('3052', '导入执行', '3022', '4', '', '', '', '', 1, 0, 'F', '0', '0', 'gs:ops:import', '#', 'admin', now(), '', null, 'Excel导入')
on conflict (menu_id) do nothing;

insert into sys_role_menu (role_id, menu_id) values ('3','3048'),('3','3049'),('3','3050'),('3','3051'),('3','3052')
on conflict do nothing;

select setval(pg_get_serial_sequence('sys_menu', 'menu_id'), (select coalesce(max(menu_id), 1) from sys_menu));
