-- 对齐清单增量（可重复执行）
alter table gs_activity add column if not exists black_word text default '';
alter table gs_activity add column if not exists danmu_history_num int4 default 30;
alter table gs_activity add column if not exists danmu_position_mode int4 default 4;
alter table gs_activity add column if not exists danmu_is_loop char(1) default '2';
alter table gs_activity add column if not exists danmu_show_name char(1) default '2';
alter table gs_activity add column if not exists display_name_style varchar(16) default 'nickname';
alter table gs_activity add column if not exists qrcode_x int4 default 24;
alter table gs_activity add column if not exists qrcode_y int4 default 24;
alter table gs_activity add column if not exists qrcode_w int4 default 120;
alter table gs_activity add column if not exists qrcode_h int4 default 120;
alter table gs_activity add column if not exists h5_entry_url varchar(512) default 'http://localhost:5174';
alter table gs_activity add column if not exists msg_color varchar(16) default '#e8eefc';
alter table gs_activity add column if not exists msg_history_num int4 default 30;
alter table gs_activity add column if not exists msg_loop char(1) default '0';

alter table gs_game_session add column if not exists duration_sec int4 default 60;

alter table gs_activity add column if not exists redpacket_tips text default '';
alter table gs_activity add column if not exists redpacket_rule text default '';
alter table gs_activity add column if not exists redpacket_send_name varchar(64) default '微信科技';
alter table gs_activity add column if not exists redpacket_wishing varchar(128) default '恭喜发财';

alter table gs_user_prize add column if not exists winner_name varchar(128) default '';
alter table gs_user_prize add column if not exists round_id int8;

alter table gs_vote add column if not exists show_type int4 default 2;
alter table gs_vote add column if not exists unit varchar(16) default '票';

-- 第四十八轮：systemsettings + 弹幕间隔 + 红包倒计时
alter table gs_activity add column if not exists screen_menu_color varchar(16) default '#dbb902';
alter table gs_activity add column if not exists show_count_sign char(1) default '2';
alter table gs_activity add column if not exists h5_menu_font_color varchar(16) default '#000000';
alter table gs_activity add column if not exists danmu_loop_time int4 default 3;

alter table gs_redpacket_round add column if not exists duration_sec int4 default 60;
alter table gs_redpacket_round add column if not exists started_at timestamp;

create table if not exists gs_sign_field (
  id int8 generated by default as identity primary key,
  activity_id int8 not null default 1,
  field_key varchar(64) not null,
  title varchar(64) not null,
  is_must char(1) default '0',
  order_num int4 default 0
);

create table if not exists gs_reserved (
  id int8 generated by default as identity primary key,
  activity_id int8 not null default 1,
  realname varchar(64),
  phone varchar(32),
  info varchar(255)
);

create table if not exists gs_import_name (
  id int8 generated by default as identity primary key,
  activity_id int8 not null default 1,
  display_name varchar(128) not null,
  phone varchar(32) default '',
  used char(1) default '0'
);

create table if not exists gs_lucky_preset (
  id int8 generated by default as identity primary key,
  activity_id int8 not null default 1,
  draw_type varchar(16) not null,
  value varchar(64) not null,
  used char(1) default '0'
);

insert into sys_menu values('2022', '运营工具', '2000', '11', 'ops', 'gamescreen/ops/index', '', '', 1, 0, 'C', '0', '0', 'gs:ops:list', 'tool', 'admin', now(), '', null, '内定/导入/预留/配对')
on conflict (menu_id) do nothing;
insert into sys_menu values('2023', '运营修改', '2022', '1', '', '', '', '', 1, 0, 'F', '0', '0', 'gs:ops:edit', '#', 'admin', now(), '', null, '')
on conflict (menu_id) do nothing;

create table if not exists gs_threedimensional (
  id int8 generated by default as identity primary key,
  activity_id int8 not null default 1 unique,
  avatar_num int4 default 120,
  avatar_size int4 default 72,
  avatar_gap int4 default 8,
  shape_sequence varchar(128) default 'helix,sphere,torus,grid,gene,earth',
  sign_sound_url varchar(512) default ''
);
insert into gs_threedimensional (activity_id) values (1) on conflict (activity_id) do nothing;

insert into sys_menu values('2024', '3D签到配置', '2000', '12', 'threed', 'gamescreen/threed/index', '', '', 1, 0, 'C', '0', '0', 'gs:threed:list', 'example', 'admin', now(), '', null, '')
on conflict (menu_id) do nothing;
insert into sys_menu values('2025', '3D签到修改', '2024', '1', '', '', '', '', 1, 0, 'F', '0', '0', 'gs:threed:edit', '#', 'admin', now(), '', null, '')
on conflict (menu_id) do nothing;

-- 幸运抽奖记录、活动创建等补充菜单（动态路由 component 对应 views/gamescreen/*）
insert into sys_menu values('2026', '幸运记录', '2000', '13', 'lucky', 'gamescreen/lucky/index', '', '', 1, 0, 'C', '0', '0', 'gs:lucky:list', 'skill', 'admin', now(), '', null, '幸运号/幸运手机号开奖记录')
on conflict (menu_id) do nothing;
insert into sys_menu values('2027', '幸运查询', '2026', '1', '', '', '', '', 1, 0, 'F', '0', '0', 'gs:lucky:query', '#', 'admin', now(), '', null, '')
on conflict (menu_id) do nothing;
insert into sys_menu values('2028', '活动创建', '2001', '3', '', '', '', '', 1, 0, 'F', '0', '0', 'gs:activity:create', '#', 'admin', now(), '', null, '')
on conflict (menu_id) do nothing;

-- 各模块查询按钮权限（与若依列表页 v-hasPermi 对齐）
insert into sys_menu values('2029', '插件查询', '2002', '2', '', '', '', '', 1, 0, 'F', '0', '0', 'gs:plug:query', '#', 'admin', now(), '', null, '')
on conflict (menu_id) do nothing;
insert into sys_menu values('2030', '观众查询', '2003', '2', '', '', '', '', 1, 0, 'F', '0', '0', 'gs:attendee:query', '#', 'admin', now(), '', null, '')
on conflict (menu_id) do nothing;
insert into sys_menu values('2031', '上墙查询', '2004', '2', '', '', '', '', 1, 0, 'F', '0', '0', 'gs:wall:query', '#', 'admin', now(), '', null, '')
on conflict (menu_id) do nothing;
insert into sys_menu values('2032', '投票查询', '2005', '2', '', '', '', '', 1, 0, 'F', '0', '0', 'gs:vote:query', '#', 'admin', now(), '', null, '')
on conflict (menu_id) do nothing;
insert into sys_menu values('2033', '奖品查询', '2006', '2', '', '', '', '', 1, 0, 'F', '0', '0', 'gs:prize:query', '#', 'admin', now(), '', null, '')
on conflict (menu_id) do nothing;
insert into sys_menu values('2034', '抽奖查询', '2007', '2', '', '', '', '', 1, 0, 'F', '0', '0', 'gs:lottery:query', '#', 'admin', now(), '', null, '')
on conflict (menu_id) do nothing;
insert into sys_menu values('2035', '游戏查询', '2008', '2', '', '', '', '', 1, 0, 'F', '0', '0', 'gs:game:query', '#', 'admin', now(), '', null, '')
on conflict (menu_id) do nothing;
insert into sys_menu values('2036', '红包查询', '2009', '2', '', '', '', '', 1, 0, 'F', '0', '0', 'gs:redpacket:query', '#', 'admin', now(), '', null, '')
on conflict (menu_id) do nothing;
insert into sys_menu values('2037', '内容查询', '2010', '2', '', '', '', '', 1, 0, 'F', '0', '0', 'gs:content:query', '#', 'admin', now(), '', null, '')
on conflict (menu_id) do nothing;
insert into sys_menu values('2038', '运营查询', '2022', '2', '', '', '', '', 1, 0, 'F', '0', '0', 'gs:ops:query', '#', 'admin', now(), '', null, '')
on conflict (menu_id) do nothing;
insert into sys_menu values('2039', '3D查询', '2024', '2', '', '', '', '', 1, 0, 'F', '0', '0', 'gs:threed:query', '#', 'admin', now(), '', null, '')
on conflict (menu_id) do nothing;
insert into sys_menu values('2040', '对对碰执行', '2022', '3', '', '', '', '', 1, 0, 'F', '0', '0', 'gs:ops:pair', '#', 'admin', now(), '', null, '')
on conflict (menu_id) do nothing;

-- 活动运营角色（仅活动大屏菜单，可在【角色管理】分配给运营账号）
insert into sys_role values('3', '活动运营', 'gamescreen', 3, 1, 1, 1, '0', '0', 'admin', now(), '', null, '活动大屏运营人员')
on conflict (role_id) do nothing;

insert into sys_role_menu (role_id, menu_id) values
  ('3','2000'),('3','2001'),('3','2002'),('3','2003'),('3','2004'),('3','2005'),('3','2006'),('3','2007'),('3','2008'),('3','2009'),('3','2010'),
  ('3','2011'),('3','2012'),('3','2013'),('3','2014'),('3','2015'),('3','2016'),('3','2017'),('3','2018'),('3','2019'),('3','2020'),('3','2021'),
  ('3','2022'),('3','2023'),('3','2024'),('3','2025'),('3','2026'),('3','2027'),('3','2028'),('3','2029'),('3','2030'),('3','2031'),('3','2032'),
  ('3','2033'),('3','2034'),('3','2035'),('3','2036'),('3','2037'),('3','2038'),('3','2039'),('3','2040')
on conflict do nothing;

-- 默认签到字段（活动 1）
insert into gs_sign_field (activity_id, field_key, title, is_must, order_num)
select 1, 'signName', '姓名', '1', 10
where not exists (select 1 from gs_sign_field where activity_id = 1 and field_key = 'signName');
insert into gs_sign_field (activity_id, field_key, title, is_must, order_num)
select 1, 'phone', '手机', '0', 20
where not exists (select 1 from gs_sign_field where activity_id = 1 and field_key = 'phone');
insert into gs_sign_field (activity_id, field_key, title, is_must, order_num)
select 1, 'sex', '性别', '1', 30
where not exists (select 1 from gs_sign_field where activity_id = 1 and field_key = 'sex');

select setval(pg_get_serial_sequence('sys_menu', 'menu_id'), (select coalesce(max(menu_id), 1) from sys_menu));

-- 第五十六轮：签到墙对齐
alter table gs_attendee add column if not exists sign_audit char(1) default '1';
alter table gs_activity add column if not exists sign_audit_mode char(1) default '0';
alter table gs_activity add column if not exists reserved_match_mode char(1) default '1';
alter table gs_activity add column if not exists reserved_verify_mode char(1) default '1';
alter table gs_sign_field add column if not exists field_type varchar(16) default 'text';
alter table gs_sign_field add column if not exists field_options text default '';
alter table gs_threedimensional add column if not exists page_sequence varchar(1024) default '';
update gs_attendee set sign_audit = '1' where sign_audit is null and signed = '1';
