-- 活动大屏业务表 + 菜单（可重复执行）
-- 库：与若依同一 PostgreSQL 库（默认 ry_vue）

create table if not exists gs_activity (
  id int8 generated by default as identity primary key,
  title varchar(128) not null default '现场活动',
  screen_password varchar(100) not null default 'screen123',
  verify_code varchar(32) default '',
  msg_audit char(1) default '0',
  time_interval int4 default 3,
  max_players int4 default 0,
  danmu_enabled char(1) default '1',
  danmu_color varchar(16) default '#b7e692',
  copyright varchar(255) default '',
  status char(1) default '0',
  create_by varchar(64) default '',
  create_time timestamp default now(),
  update_by varchar(64) default '',
  update_time timestamp
);

create table if not exists gs_plug (
  id int8 generated by default as identity primary key,
  activity_id int8 not null default 1,
  name varchar(64) not null,
  title varchar(64) not null,
  enabled char(1) default '0',
  order_num int4 default 0,
  hotkey varchar(32) default '',
  is_module char(1) default '0',
  unique (activity_id, name)
);

create table if not exists gs_attendee (
  id int8 generated by default as identity primary key,
  activity_id int8 not null default 1,
  openid varchar(64) not null,
  nickname varchar(128) default '',
  avatar varchar(512) default '',
  phone varchar(20) default '',
  sign_name varchar(64) default '',
  sex varchar(8) default '',
  signed char(1) default '0',
  status char(1) default '0',
  sign_order int4,
  extra jsonb,
  create_time timestamp default now(),
  unique (activity_id, openid)
);

create table if not exists gs_wall_message (
  id int8 generated by default as identity primary key,
  activity_id int8 not null default 1,
  attendee_id int8,
  nickname varchar(128),
  avatar varchar(512),
  content text,
  image_url varchar(512),
  audit_status char(1) default '1',
  create_time timestamp default now()
);

create table if not exists gs_vote (
  id int8 generated by default as identity primary key,
  activity_id int8 not null default 1,
  title varchar(128) not null,
  max_select int4 default 1,
  status char(1) default '0',
  show_type int4 default 2,
  unit varchar(16) default '票',
  create_time timestamp default now()
);

create table if not exists gs_vote_item (
  id int8 generated by default as identity primary key,
  vote_id int8 not null,
  name varchar(128) not null,
  cover varchar(512) default '',
  votes int4 default 0,
  order_num int4 default 0
);

create table if not exists gs_vote_record (
  id int8 generated by default as identity primary key,
  vote_id int8 not null,
  item_id int8 not null,
  attendee_id int8 not null,
  create_time timestamp default now(),
  unique (vote_id, attendee_id, item_id)
);

create table if not exists gs_prize (
  id int8 generated by default as identity primary key,
  activity_id int8 not null default 1,
  plug_name varchar(64) not null,
  name varchar(128) not null,
  image_url varchar(512) default '',
  total_num int4 default 1,
  left_num int4 default 1,
  create_time timestamp default now()
);

create table if not exists gs_user_prize (
  id int8 generated by default as identity primary key,
  activity_id int8 not null default 1,
  prize_id int8,
  attendee_id int8,
  plug_name varchar(64),
  designated char(1) default '0',
  create_time timestamp default now()
);

create table if not exists gs_lucky_draw (
  id int8 generated by default as identity primary key,
  activity_id int8 not null default 1,
  draw_type varchar(32) not null,
  value varchar(64) not null,
  attendee_id int8,
  create_time timestamp default now()
);

create table if not exists gs_lottery_config (
  id int8 generated by default as identity primary key,
  activity_id int8 not null default 1,
  plug_name varchar(64) not null,
  title varchar(128) default '',
  theme varchar(64) default 'cjx',
  win_again char(1) default '0',
  extra jsonb,
  unique (activity_id, plug_name)
);

create table if not exists gs_game_session (
  id int8 generated by default as identity primary key,
  activity_id int8 not null default 1,
  theme varchar(64) not null default 'car',
  status varchar(16) not null default 'idle',
  started_at timestamp,
  ended_at timestamp
);

create table if not exists gs_game_record (
  id int8 generated by default as identity primary key,
  session_id int8 not null,
  attendee_id int8 not null,
  score int4 default 0,
  unique (session_id, attendee_id)
);

create table if not exists gs_redpacket_round (
  id int8 generated by default as identity primary key,
  activity_id int8 not null default 1,
  title varchar(128) default '红包雨',
  total_amount numeric(10,2) default 0,
  packet_num int4 default 0,
  left_num int4 default 0,
  status varchar(16) default 'idle',
  create_time timestamp default now()
);

create table if not exists gs_redpacket_grab (
  id int8 generated by default as identity primary key,
  round_id int8 not null,
  attendee_id int8 not null,
  amount numeric(10,2) default 0,
  pay_status varchar(16) default 'mock',
  create_time timestamp default now(),
  unique (round_id, attendee_id)
);

create table if not exists gs_content (
  id int8 generated by default as identity primary key,
  activity_id int8 not null default 1,
  content_type varchar(32) not null,
  title varchar(128) default '',
  body text,
  image_url varchar(512),
  order_num int4 default 0,
  extra jsonb,
  create_time timestamp default now()
);

create table if not exists gs_pair (
  id int8 generated by default as identity primary key,
  activity_id int8 not null default 1,
  left_attendee_id int8,
  right_attendee_id int8,
  create_time timestamp default now()
);

insert into gs_activity (id, title, screen_password, verify_code, copyright)
select 1, '现场活动大屏', 'screen123', 'demo', 'GameScreen'
where not exists (select 1 from gs_activity where id = 1);

insert into gs_plug (activity_id, name, title, enabled, order_num, hotkey, is_module)
select 1, v.name, v.title, v.enabled, v.ord, v.hotkey, v.mod
from (values
  ('qdq','签到墙','0',1,'ctrl+1','0'),
  ('threedimensionalsign','3D签到','0',2,'ctrl+2','0'),
  ('wall','微信上墙','0',3,'ctrl+3','0'),
  ('vote','投票','0',5,'ctrl+5','0'),
  ('xyh','幸运号码','0',7,'ctrl+6','0'),
  ('xysjh','幸运手机号','0',8,'ctrl+7','0'),
  ('ddp','对对碰','0',10,'ctrl+8','0'),
  ('xiangce','相册','0',12,'ctrl+9','0'),
  ('kaimu','开幕墙','0',14,'ctrl+k','0'),
  ('bimu','闭幕墙','0',15,'ctrl+b','0'),
  ('redpacket','红包雨','1',16,'ctrl+r','0'),
  ('danye','单页','0',25,'','0'),
  ('hyxc','活动行程','0',26,'','0'),
  ('ydj','摇大奖','0',20,'ctrl+y','1'),
  ('choujiang','手机端抽奖','0',21,'','1'),
  ('importlottery','导入抽奖','0',22,'','1'),
  ('lottery','抽奖','0',23,'ctrl+l','1'),
  ('game','游戏','0',24,'ctrl+x','1')
) as v(name, title, enabled, ord, hotkey, mod)
where not exists (select 1 from gs_plug p where p.activity_id = 1 and p.name = v.name);

insert into gs_lottery_config (activity_id, plug_name, title, theme)
select 1, v.plug, v.title, v.theme
from (values
  ('lottery','大屏抽奖','cjx'),
  ('ydj','摇大奖','default'),
  ('choujiang','刮刮卡','guaguaka'),
  ('importlottery','导入抽奖','import'),
  ('game','竞速游戏','car')
) as v(plug, title, theme)
where not exists (select 1 from gs_lottery_config c where c.activity_id = 1 and c.plug_name = v.plug);

insert into gs_vote (id, activity_id, title, max_select, status)
select 1, 1, '你最喜欢哪个环节？', 1, '0'
where not exists (select 1 from gs_vote where id = 1);

insert into gs_vote_item (vote_id, name, order_num)
select 1, v.name, v.ord from (values ('签到墙',1),('上墙互动',2),('抽奖',3),('游戏',4)) as v(name,ord)
where not exists (select 1 from gs_vote_item i where i.vote_id = 1);

-- 菜单 2000+
insert into sys_menu values('2000', '活动大屏', '0', '5', 'gamescreen', null, '', '', 1, 0, 'M', '0', '0', '', 'guide', 'admin', now(), '', null, '活动大屏目录')
on conflict (menu_id) do nothing;
insert into sys_menu values('2001', '活动配置', '2000', '1', 'activity', 'gamescreen/activity/index', '', '', 1, 0, 'C', '0', '0', 'gs:activity:list', 'edit', 'admin', now(), '', null, '活动配置')
on conflict (menu_id) do nothing;
insert into sys_menu values('2002', '功能开关', '2000', '2', 'plug', 'gamescreen/plug/index', '', '', 1, 0, 'C', '0', '0', 'gs:plug:list', 'switch', 'admin', now(), '', null, '插件开关')
on conflict (menu_id) do nothing;
insert into sys_menu values('2003', '签到用户', '2000', '3', 'attendee', 'gamescreen/attendee/index', '', '', 1, 0, 'C', '0', '0', 'gs:attendee:list', 'peoples', 'admin', now(), '', null, '观众')
on conflict (menu_id) do nothing;
insert into sys_menu values('2004', '上墙审核', '2000', '4', 'wall', 'gamescreen/wall/index', '', '', 1, 0, 'C', '0', '0', 'gs:wall:list', 'message', 'admin', now(), '', null, '上墙')
on conflict (menu_id) do nothing;
insert into sys_menu values('2005', '投票管理', '2000', '5', 'vote', 'gamescreen/vote/index', '', '', 1, 0, 'C', '0', '0', 'gs:vote:list', 'list', 'admin', now(), '', null, '投票')
on conflict (menu_id) do nothing;
insert into sys_menu values('2006', '奖品中台', '2000', '6', 'prize', 'gamescreen/prize/index', '', '', 1, 0, 'C', '0', '0', 'gs:prize:list', 'star', 'admin', now(), '', null, '奖品')
on conflict (menu_id) do nothing;
insert into sys_menu values('2007', '抽奖玩法', '2000', '7', 'lottery', 'gamescreen/lottery/index', '', '', 1, 0, 'C', '0', '0', 'gs:lottery:list', 'guide', 'admin', now(), '', null, '抽奖')
on conflict (menu_id) do nothing;
insert into sys_menu values('2008', '竞速游戏', '2000', '8', 'game', 'gamescreen/game/index', '', '', 1, 0, 'C', '0', '0', 'gs:game:list', 'example', 'admin', now(), '', null, '游戏')
on conflict (menu_id) do nothing;
insert into sys_menu values('2009', '红包雨', '2000', '9', 'redpacket', 'gamescreen/redpacket/index', '', '', 1, 0, 'C', '0', '0', 'gs:redpacket:list', 'money', 'admin', now(), '', null, '红包')
on conflict (menu_id) do nothing;
insert into sys_menu values('2010', '展示内容', '2000', '10', 'content', 'gamescreen/content/index', '', '', 1, 0, 'C', '0', '0', 'gs:content:list', 'documentation', 'admin', now(), '', null, '开闭幕相册单页行程')
on conflict (menu_id) do nothing;

insert into sys_menu values('2011', '活动查询', '2001', '1', '', '', '', '', 1, 0, 'F', '0', '0', 'gs:activity:query', '#', 'admin', now(), '', null, '')
on conflict (menu_id) do nothing;
insert into sys_menu values('2012', '活动修改', '2001', '2', '', '', '', '', 1, 0, 'F', '0', '0', 'gs:activity:edit', '#', 'admin', now(), '', null, '')
on conflict (menu_id) do nothing;
insert into sys_menu values('2013', '插件修改', '2002', '1', '', '', '', '', 1, 0, 'F', '0', '0', 'gs:plug:edit', '#', 'admin', now(), '', null, '')
on conflict (menu_id) do nothing;
insert into sys_menu values('2014', '用户修改', '2003', '1', '', '', '', '', 1, 0, 'F', '0', '0', 'gs:attendee:edit', '#', 'admin', now(), '', null, '')
on conflict (menu_id) do nothing;
insert into sys_menu values('2015', '上墙审核', '2004', '1', '', '', '', '', 1, 0, 'F', '0', '0', 'gs:wall:edit', '#', 'admin', now(), '', null, '')
on conflict (menu_id) do nothing;
insert into sys_menu values('2016', '投票修改', '2005', '1', '', '', '', '', 1, 0, 'F', '0', '0', 'gs:vote:edit', '#', 'admin', now(), '', null, '')
on conflict (menu_id) do nothing;
insert into sys_menu values('2017', '奖品修改', '2006', '1', '', '', '', '', 1, 0, 'F', '0', '0', 'gs:prize:edit', '#', 'admin', now(), '', null, '')
on conflict (menu_id) do nothing;
insert into sys_menu values('2018', '抽奖执行', '2007', '1', '', '', '', '', 1, 0, 'F', '0', '0', 'gs:lottery:edit', '#', 'admin', now(), '', null, '')
on conflict (menu_id) do nothing;
insert into sys_menu values('2019', '游戏控制', '2008', '1', '', '', '', '', 1, 0, 'F', '0', '0', 'gs:game:edit', '#', 'admin', now(), '', null, '')
on conflict (menu_id) do nothing;
insert into sys_menu values('2020', '红包控制', '2009', '1', '', '', '', '', 1, 0, 'F', '0', '0', 'gs:redpacket:edit', '#', 'admin', now(), '', null, '')
on conflict (menu_id) do nothing;
insert into sys_menu values('2021', '内容修改', '2010', '1', '', '', '', '', 1, 0, 'F', '0', '0', 'gs:content:edit', '#', 'admin', now(), '', null, '')
on conflict (menu_id) do nothing;

select setval(pg_get_serial_sequence('sys_menu', 'menu_id'), (select coalesce(max(menu_id), 1) from sys_menu));
select setval(pg_get_serial_sequence('gs_activity', 'id'), (select coalesce(max(id), 1) from gs_activity));
select setval(pg_get_serial_sequence('gs_vote', 'id'), (select coalesce(max(id), 1) from gs_vote));
