-- N4 light error-cause tags on score questions (idempotent)
-- Apply: psql -f sql/spas_error_tag.sql  OR  python sql/spas_apply_incremental.py

create table if not exists spas_error_tag (
  tag_id int8 generated by default as identity not null,
  student_id int8 not null,
  paper_id int8 not null,
  question_id int8 not null,
  error_code varchar(32) not null,
  remark varchar(200),
  create_by varchar(64) default '',
  create_time timestamp,
  update_by varchar(64) default '',
  update_time timestamp,
  primary key (tag_id)
);
create unique index if not exists uk_spas_error_tag_stu_q
  on spas_error_tag (student_id, question_id);
create index if not exists idx_spas_error_tag_student on spas_error_tag(student_id);
create index if not exists idx_spas_error_tag_paper on spas_error_tag(paper_id);
comment on table spas_error_tag is 'teacher-tagged error cause per student question';
comment on column spas_error_tag.error_code is 'reading|calc|concept|skip';

insert into sys_dict_type(dict_name, dict_type, status, create_by, create_time, remark)
select '错因标签', 'spas_error_cause', '0', 'admin', now(), 'N4 light error tags'
where not exists (select 1 from sys_dict_type where dict_type='spas_error_cause');

insert into sys_dict_data(dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time)
select * from (values
 (1, '审题', 'reading', 'spas_error_cause', '', 'warning', 'N', '0', 'admin', now()),
 (2, '计算', 'calc', 'spas_error_cause', '', 'danger', 'N', '0', 'admin', now()),
 (3, '概念', 'concept', 'spas_error_cause', '', 'primary', 'N', '0', 'admin', now()),
 (4, '未做', 'skip', 'spas_error_cause', '', 'info', 'N', '0', 'admin', now())
) as v(dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time)
where not exists (select 1 from sys_dict_data d where d.dict_type='spas_error_cause' and d.dict_value=v.dict_value);
