-- Subject-scoped question types + widen paper question_type
ALTER TABLE spas_paper_question ALTER COLUMN question_type TYPE varchar(32);

DROP TABLE IF EXISTS spas_subject_question_type CASCADE;
CREATE TABLE spas_subject_question_type (
  type_id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  subject_id int8 NOT NULL,
  type_code varchar(32) NOT NULL,
  type_name varchar(64) NOT NULL,
  sort int4 DEFAULT 0,
  status char(1) DEFAULT '0',
  create_by varchar(64) DEFAULT '',
  create_time timestamp,
  update_by varchar(64) DEFAULT '',
  update_time timestamp,
  remark varchar(500),
  PRIMARY KEY (type_id),
  CONSTRAINT uk_spas_subject_qtype UNIQUE (subject_id, type_code)
);
CREATE INDEX idx_spas_subject_qtype_subject ON spas_subject_question_type(subject_id);
COMMENT ON TABLE spas_subject_question_type IS 'subject question type';
COMMENT ON COLUMN spas_paper_question.question_type IS 'type_code of spas_subject_question_type';

-- Seed defaults for MATH (and any subject without types)
INSERT INTO spas_subject_question_type(subject_id, type_code, type_name, sort, status, create_by, create_time)
SELECT s.subject_id, v.code, v.name, v.sort, '0', 'admin', now()
FROM spas_subject s
CROSS JOIN (VALUES
  ('single', U&'\5355\9009\9898', 1),
  ('multi',  U&'\591a\9009\9898', 2),
  ('judge',  U&'\5224\65ad\9898', 3),
  ('fill',   U&'\586b\7a7a\9898', 4),
  ('short',  U&'\7b80\7b54\9898', 5),
  ('calc',   U&'\8ba1\7b97\9898', 6)
) AS v(code, name, sort)
WHERE NOT EXISTS (
  SELECT 1 FROM spas_subject_question_type t
  WHERE t.subject_id = s.subject_id AND t.type_code = v.code
);
