-- Idempotent init for exam score tables (no DROP). Safe for spas_apply_incremental.

create table if not exists spas_exam (
  exam_id int8 generated by default as identity not null,
  exam_name varchar(128) not null,
  exam_date date,
  dept_id int8 not null,
  file_name varchar(255),
  total_rows int4 default 0,
  success_rows int4 default 0,
  fail_rows int4 default 0,
  status varchar(1) default '0',
  error_log text,
  create_by varchar(64) default '',
  create_time timestamp,
  update_by varchar(64) default '',
  update_time timestamp,
  remark varchar(500),
  primary key (exam_id)
);
create index if not exists idx_spas_exam_dept on spas_exam(dept_id, exam_date desc nulls last);

create table if not exists spas_exam_score (
  score_id int8 generated by default as identity not null,
  exam_id int8 not null,
  student_id int8 not null,
  score_type varchar(1) not null,
  subject_name varchar(64),
  score numeric(10,2),
  school_rank int4,
  create_time timestamp,
  update_time timestamp,
  primary key (score_id)
);

-- migrate legacy subject_id if present
alter table spas_exam_score add column if not exists subject_name varchar(64);

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_name = 'spas_exam_score' and column_name = 'subject_id'
  ) then
    execute $u$
      update spas_exam_score s
      set subject_name = sub.subject_name
      from spas_subject sub
      where s.subject_id is not null
        and s.subject_id = sub.subject_id
        and (s.subject_name is null or s.subject_name = '')
    $u$;
    alter table spas_exam_score drop column if exists subject_id;
  end if;
end $$;

drop index if exists uk_spas_exam_score;
create unique index uk_spas_exam_score
  on spas_exam_score (exam_id, student_id, score_type, (coalesce(subject_name, '')));

create index if not exists idx_spas_exam_score_exam on spas_exam_score(exam_id);
create index if not exists idx_spas_exam_score_student on spas_exam_score(student_id);
