-- SPAS schema for PostgreSQL
-- Student Performance Analysis System

-- 1 subject
drop table if exists spas_subject cascade;
create table spas_subject (
  subject_id int8 generated by default as identity not null,
  subject_name varchar(64) not null,
  subject_code varchar(32) not null,
  sort int4 default 0,
  status char(1) default '0',
  create_by varchar(64) default '',
  create_time timestamp,
  update_by varchar(64) default '',
  update_time timestamp,
  remark varchar(500),
  primary key (subject_id),
  constraint uk_spas_subject_code unique (subject_code)
);
comment on table spas_subject is 'subject';
comment on column spas_subject.subject_name is 'subject name';
comment on column spas_subject.subject_code is 'subject code';

-- 2 knowledge tree
drop table if exists spas_knowledge cascade;
create table spas_knowledge (
  knowledge_id int8 generated by default as identity not null,
  subject_id int8 not null,
  parent_id int8 default 0,
  ancestors varchar(500) default '',
  knowledge_name varchar(100) not null,
  knowledge_code varchar(64) default null,
  knowledge_default char(1) default '2',
  node_type char(1) default '2',
  order_num int4 default 0,
  status char(1) default '0',
  create_by varchar(64) default '',
  create_time timestamp,
  update_by varchar(64) default '',
  update_time timestamp,
  remark varchar(500),
  primary key (knowledge_id)
);
create index idx_spas_knowledge_subject on spas_knowledge(subject_id, parent_id);
comment on table spas_knowledge is 'knowledge point';
comment on column spas_knowledge.difficulty_default is '1 easy 2 medium 3 hard';
comment on column spas_knowledge.node_type is '1 chapter 2 knowledge';

-- 3 student (must bind sys_user)
drop table if exists spas_student cascade;
create table spas_student (
  student_id int8 generated by default as identity not null,
  student_no varchar(32) not null,
  student_name varchar(64) not null,
  gender char(1) default '0',
  dept_id int8 not null,
  grade_year varchar(16) default null,
  user_id int8 not null,
  parent_mobile varchar(20) default null,
  status char(1) default '0',
  del_flag char(1) default '0',
  create_by varchar(64) default '',
  create_time timestamp,
  update_by varchar(64) default '',
  update_time timestamp,
  remark varchar(500),
  primary key (student_id),
  constraint uk_spas_student_no unique (student_no),
  constraint uk_spas_student_user unique (user_id)
);
create index idx_spas_student_dept on spas_student(dept_id);
comment on table spas_student is 'student profile bound to sys_user';

-- 4 paper
drop table if exists spas_paper cascade;
create table spas_paper (
  paper_id int8 generated by default as identity not null,
  paper_name varchar(128) not null,
  paper_type char(1) not null,
  subject_id int8 not null,
  dept_id int8 not null,
  exam_date date,
  total_score numeric(8,2) default 0,
  status char(1) default '0',
  publish_time timestamp,
  create_by varchar(64) default '',
  create_time timestamp,
  update_by varchar(64) default '',
  update_time timestamp,
  remark varchar(500),
  primary key (paper_id)
);
create index idx_spas_paper_dept on spas_paper(dept_id, subject_id);
comment on table spas_paper is 'exam or homework paper';
comment on column spas_paper.paper_type is '1 exam 2 homework';
comment on column spas_paper.status is '0 draft 1 published 2 archived';

-- 5 question (no single knowledge_id)
drop table if exists spas_paper_question cascade;
create table spas_paper_question (
  question_id int8 generated by default as identity not null,
  paper_id int8 not null,
  question_no varchar(32) not null,
  question_order int4 default 0,
  full_score numeric(8,2) not null,
  difficulty char(1) default '2',
  question_type varchar(32) default null,
  remark varchar(255),
  create_by varchar(64) default '',
  create_time timestamp,
  update_by varchar(64) default '',
  update_time timestamp,
  primary key (question_id),
  constraint uk_spas_paper_question_no unique (paper_id, question_no)
);
comment on table spas_paper_question is 'paper question item';
comment on column spas_paper_question.difficulty is '1 easy 2 medium 3 hard';
comment on column spas_paper_question.question_type is 'type_code of spas_subject_question_type';

-- 5b subject question type catalog
drop table if exists spas_subject_question_type cascade;
create table spas_subject_question_type (
  type_id int8 generated by default as identity not null,
  subject_id int8 not null,
  type_code varchar(32) not null,
  type_name varchar(64) not null,
  sort int4 default 0,
  status char(1) default '0',
  create_by varchar(64) default '',
  create_time timestamp,
  update_by varchar(64) default '',
  update_time timestamp,
  remark varchar(500),
  primary key (type_id),
  constraint uk_spas_subject_qtype unique (subject_id, type_code)
);
create index idx_spas_subject_qtype_subject on spas_subject_question_type(subject_id);
comment on table spas_subject_question_type is 'subject question type';

-- 6 question-knowledge many-to-many
drop table if exists spas_question_knowledge cascade;
create table spas_question_knowledge (
  id int8 generated by default as identity not null,
  question_id int8 not null,
  knowledge_id int8 not null,
  weight numeric(6,4) not null default 1.0000,
  is_primary char(1) default '0',
  primary key (id),
  constraint uk_spas_qk unique (question_id, knowledge_id)
);
create index idx_spas_qk_knowledge on spas_question_knowledge(knowledge_id);
comment on table spas_question_knowledge is 'question knowledge weight, sum(weight)=1 per question';

-- 7 score batch
drop table if exists spas_score_batch cascade;
create table spas_score_batch (
  batch_id int8 generated by default as identity not null,
  paper_id int8 not null,
  file_name varchar(255),
  total_rows int4 default 0,
  success_rows int4 default 0,
  fail_rows int4 default 0,
  status char(1) default '0',
  error_log text,
  create_by varchar(64) default '',
  create_time timestamp,
  primary key (batch_id)
);
comment on table spas_score_batch is 'score import batch';

-- 8 score detail
drop table if exists spas_score_detail cascade;
create table spas_score_detail (
  detail_id int8 generated by default as identity not null,
  paper_id int8 not null,
  question_id int8 not null,
  student_id int8 not null,
  batch_id int8,
  score numeric(8,2) not null,
  full_score numeric(8,2) not null,
  rate numeric(6,4) not null,
  prev_batch_id int8,
  prev_score numeric(8,2),
  prev_full_score numeric(8,2),
  prev_rate numeric(6,4),
  create_time timestamp,
  update_time timestamp,
  primary key (detail_id),
  constraint uk_spas_score_detail unique (paper_id, question_id, student_id)
);
create index idx_spas_score_student on spas_score_detail(student_id, paper_id);
comment on table spas_score_detail is 'student question score';
comment on column spas_score_detail.prev_batch_id is 'previous batch before last upsert (for revoke restore)';

-- 9 knowledge stat snapshot
drop table if exists spas_student_knowledge_stat cascade;
create table spas_student_knowledge_stat (
  stat_id int8 generated by default as identity not null,
  student_id int8 not null,
  knowledge_id int8 not null,
  subject_id int8 not null,
  attempt_count int4 default 0,
  avg_rate numeric(6,4) default 0,
  weighted_rate numeric(6,4) default 0,
  last_paper_id int8,
  last_exam_date date,
  weak_level char(1) default '0',
  calc_time timestamp,
  primary key (stat_id),
  constraint uk_spas_sk_stat unique (student_id, knowledge_id)
);
create index idx_spas_sk_stat_subject on spas_student_knowledge_stat(subject_id, weak_level);
comment on table spas_student_knowledge_stat is 'student knowledge snapshot';
comment on column spas_student_knowledge_stat.weak_level is '0 normal 1 watch 2 weak 3 severe';

-- 10 warning rule
drop table if exists spas_warning_rule cascade;
create table spas_warning_rule (
  rule_id int8 generated by default as identity not null,
  rule_name varchar(64) not null,
  rule_code varchar(64) not null,
  scope_type char(1) default '1',
  scope_id int8,
  metric varchar(32) not null,
  operator varchar(8) default '<',
  threshold numeric(10,4) not null,
  window_days int4 default 30,
  level char(1) default '1',
  enabled char(1) default '1',
  notify_channels varchar(64) default 'system',
  create_by varchar(64) default '',
  create_time timestamp,
  update_by varchar(64) default '',
  update_time timestamp,
  remark varchar(500),
  primary key (rule_id),
  constraint uk_spas_warning_rule_code unique (rule_code)
);
comment on table spas_warning_rule is 'warning rule';

-- 11 warning record
drop table if exists spas_warning_record cascade;
create table spas_warning_record (
  warning_id int8 generated by default as identity not null,
  rule_id int8,
  student_id int8 not null,
  subject_id int8,
  knowledge_id int8,
  paper_id int8,
  level char(1) default '1',
  title varchar(128) not null,
  content varchar(1000),
  metric_value numeric(10,4),
  status char(1) default '0',
  handle_by varchar(64),
  handle_time timestamp,
  handle_remark varchar(500),
  create_time timestamp,
  primary key (warning_id)
);
create index idx_spas_warning_student on spas_warning_record(student_id, status);
comment on table spas_warning_record is 'warning record';

-- 12 coach log
drop table if exists spas_coach_log cascade;
create table spas_coach_log (
  log_id int8 generated by default as identity not null,
  student_id int8 not null,
  warning_id int8,
  content varchar(2000) not null,
  next_plan varchar(1000),
  create_by varchar(64) default '',
  create_time timestamp,
  primary key (log_id)
);
comment on table spas_coach_log is 'coaching log for portfolio';

-- 13 parent open reserved
drop table if exists spas_parent cascade;
create table spas_parent (
  parent_id int8 generated by default as identity not null,
  parent_name varchar(64),
  mobile varchar(20),
  status char(1) default '0',
  create_time timestamp,
  primary key (parent_id)
);

drop table if exists spas_parent_student cascade;
create table spas_parent_student (
  id int8 generated by default as identity not null,
  parent_id int8 not null,
  student_id int8 not null,
  bind_status char(1) default '0',
  create_time timestamp,
  primary key (id),
  constraint uk_spas_parent_student unique (parent_id, student_id)
);

drop table if exists spas_open_client cascade;
create table spas_open_client (
  client_id int8 generated by default as identity not null,
  app_id varchar(64) not null,
  app_secret varchar(128) not null,
  app_name varchar(64),
  status char(1) default '0',
  create_time timestamp,
  primary key (client_id),
  constraint uk_spas_open_app unique (app_id)
);
