-- D5: knowledge prerequisite edges (idempotent)
CREATE TABLE IF NOT EXISTS spas_knowledge_edge (
  edge_id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  subject_id int8 NOT NULL,
  from_knowledge_id int8 NOT NULL,
  to_knowledge_id int8 NOT NULL,
  relation varchar(32) NOT NULL DEFAULT 'prerequisite',
  weight numeric(8,4) DEFAULT 1,
  status char(1) DEFAULT '0',
  create_by varchar(64) DEFAULT '',
  create_time timestamp,
  update_by varchar(64) DEFAULT '',
  update_time timestamp,
  remark varchar(500),
  PRIMARY KEY (edge_id),
  CONSTRAINT uk_spas_knowledge_edge UNIQUE (from_knowledge_id, to_knowledge_id, relation)
);
CREATE INDEX IF NOT EXISTS idx_spas_knowledge_edge_subject ON spas_knowledge_edge(subject_id);
CREATE INDEX IF NOT EXISTS idx_spas_knowledge_edge_to ON spas_knowledge_edge(to_knowledge_id);
CREATE INDEX IF NOT EXISTS idx_spas_knowledge_edge_from ON spas_knowledge_edge(from_knowledge_id);
COMMENT ON TABLE spas_knowledge_edge IS 'knowledge prerequisite edges: from = prerequisite of to';
