-- F1 intervene closed-loop (phase 2)
-- Apply: psql -U postgres -d spas-sql -f sql/spas_intervene.sql

create table if not exists spas_intervene_task (
  intervene_id int8 generated by default as identity not null,
  student_id int8 not null,
  subject_id int8,
  source_type char(1) default '3',
  source_id int8,
  knowledge_ids varchar(500),
  title varchar(128) not null,
  target_rate numeric(10,6) default 0.60,
  baseline_rate numeric(10,6),
  baseline_json text,
  status char(1) default '0',
  owner_by varchar(64) default '',
  due_date date,
  close_time timestamp,
  effect_rate numeric(10,6),
  effect_delta numeric(10,6),
  effect_passed char(1) default '0',
  create_by varchar(64) default '',
  create_time timestamp,
  update_by varchar(64) default '',
  update_time timestamp,
  remark varchar(500),
  primary key (intervene_id)
);
create index if not exists idx_spas_intervene_student on spas_intervene_task(student_id, status);
create index if not exists idx_spas_intervene_status on spas_intervene_task(status);
comment on table spas_intervene_task is 'intervention task: warning/weak -> coach -> retest';
comment on column spas_intervene_task.source_type is '1=warning 2=weak-knowledge 3=manual';
comment on column spas_intervene_task.status is '0=open 1=passed 2=closed 3=overdue';

alter table spas_coach_log add column if not exists intervene_id int8;
alter table spas_coach_log add column if not exists knowledge_id int8;
create index if not exists idx_spas_coach_intervene on spas_coach_log(intervene_id);

insert into sys_dict_type(dict_name, dict_type, status, create_by, create_time, remark)
select '干预状态', 'spas_intervene_status', '0', 'admin', now(), null
where not exists (select 1 from sys_dict_type where dict_type='spas_intervene_status');

insert into sys_dict_type(dict_name, dict_type, status, create_by, create_time, remark)
select '干预来源', 'spas_intervene_source', '0', 'admin', now(), null
where not exists (select 1 from sys_dict_type where dict_type='spas_intervene_source');

insert into sys_dict_data(dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time)
select * from (values
 (1, '进行中', '0', 'spas_intervene_status', '', 'primary', 'Y', '0', 'admin', now()),
 (2, '已达标', '1', 'spas_intervene_status', '', 'success', 'N', '0', 'admin', now()),
 (3, '已关闭', '2', 'spas_intervene_status', '', 'info', 'N', '0', 'admin', now()),
 (4, '逾期', '3', 'spas_intervene_status', '', 'danger', 'N', '0', 'admin', now())
) as v(dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time)
where not exists (select 1 from sys_dict_data d where d.dict_type='spas_intervene_status' and d.dict_value=v.dict_value);

insert into sys_dict_data(dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time)
select * from (values
 (1, '预警', '1', 'spas_intervene_source', '', 'warning', 'N', '0', 'admin', now()),
 (2, '薄弱点', '2', 'spas_intervene_source', '', 'danger', 'N', '0', 'admin', now()),
 (3, '手动', '3', 'spas_intervene_source', '', 'info', 'Y', '0', 'admin', now())
) as v(dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time)
where not exists (select 1 from sys_dict_data d where d.dict_type='spas_intervene_source' and d.dict_value=v.dict_value);

insert into sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, remark)
select 2085, '干预任务', 2000, 6, 'intervene', 'spas/intervene/index', '', '', 1, 0, 'C', '0', '0', 'spas:intervene:list', 'guide', 'admin', now(), 'intervention closed-loop'
where not exists (select 1 from sys_menu where menu_id=2085);

insert into sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time)
select 2086, '干预查询', 2085, 1, '', '', '', '', 1, 0, 'F', '0', '0', 'spas:intervene:list', '#', 'admin', now()
where not exists (select 1 from sys_menu where menu_id=2086);

insert into sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time)
select 2087, '干预新增', 2085, 2, '', '', '', '', 1, 0, 'F', '0', '0', 'spas:intervene:add', '#', 'admin', now()
where not exists (select 1 from sys_menu where menu_id=2087);

insert into sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time)
select 2088, '干预修改', 2085, 3, '', '', '', '', 1, 0, 'F', '0', '0', 'spas:intervene:edit', '#', 'admin', now()
where not exists (select 1 from sys_menu where menu_id=2088);

insert into sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time)
select 2089, '效果评估', 2085, 4, '', '', '', '', 1, 0, 'F', '0', '0', 'spas:intervene:handle', '#', 'admin', now()
where not exists (select 1 from sys_menu where menu_id=2089);

insert into sys_role_menu(role_id, menu_id)
select r.role_id, m.menu_id
from sys_role r
cross join (values (2085),(2086),(2087),(2088),(2089)) as m(menu_id)
where r.role_key in ('admin', 'spas_admin', 'spas_jw', 'spas_teacher', 'spas_bzr', 'spas_grade_leader', 'spas_school_leader')
  and not exists (
    select 1 from sys_role_menu rm where rm.role_id = r.role_id and rm.menu_id = m.menu_id
  );
