-- Teacher profile table (PostgreSQL, idempotent)

create table if not exists spas_teacher (
  teacher_id int8 generated by default as identity not null,
  teacher_no varchar(32) not null,
  teacher_name varchar(64) not null,
  teacher_type char(1) not null default '1',
  dept_id int8 not null,
  user_id int8 not null,
  mobile varchar(20) default null,
  gender char(1) default '0',
  status char(1) default '0',
  del_flag char(1) default '0',
  create_by varchar(64) default '',
  create_time timestamp,
  update_by varchar(64) default '',
  update_time timestamp,
  remark varchar(500),
  primary key (teacher_id),
  constraint uk_spas_teacher_no unique (teacher_no),
  constraint uk_spas_teacher_user unique (user_id)
);
create index if not exists idx_spas_teacher_dept on spas_teacher(dept_id);
create index if not exists idx_spas_teacher_type on spas_teacher(teacher_type);

-- dict: teacher type
insert into sys_dict_type(dict_name, dict_type, status, create_by, create_time, remark)
select U&'\6559\5e08\7c7b\578b', 'spas_teacher_type', '0', 'admin', now(), 'SPAS teacher role type'
where not exists (select 1 from sys_dict_type where dict_type = 'spas_teacher_type');

insert into sys_dict_data(dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time)
select * from (values
 (1, U&'\4efb\8bfe\6559\5e08', '1', 'spas_teacher_type', '', 'primary', 'Y', '0', 'admin', now()),
 (2, U&'\73ed\4e3b\4efb', '2', 'spas_teacher_type', '', 'success', 'N', '0', 'admin', now()),
 (3, U&'\5e74\7ea7\8d1f\8d23\4eba', '3', 'spas_teacher_type', '', 'warning', 'N', '0', 'admin', now()),
 (4, U&'\6821\7ea7\9886\5bfc', '4', 'spas_teacher_type', '', 'danger', 'N', '0', 'admin', now())
) as v(dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time)
where not exists (
  select 1 from sys_dict_data d where d.dict_type = v.dict_type and d.dict_value = v.dict_value
);
