-- SPAS exam subject scores + school ranks (multi-subject roster import)
-- Independent from spas_score_detail and spas_subject. Display only.

drop table if exists spas_exam_score cascade;
drop table if exists spas_exam cascade;

create table spas_exam (
  exam_id int8 generated by default as identity not null,
  exam_name varchar(128) not null,
  exam_date date,
  dept_id int8 not null,
  file_name varchar(255),
  total_rows int4 default 0,
  success_rows int4 default 0,
  fail_rows int4 default 0,
  status varchar(1) default '0',
  error_log text,
  create_by varchar(64) default '',
  create_time timestamp,
  update_by varchar(64) default '',
  update_time timestamp,
  remark varchar(500),
  primary key (exam_id)
);
create index idx_spas_exam_dept on spas_exam(dept_id, exam_date desc nulls last);
comment on table spas_exam is 'multi-subject exam import batch (score + school rank)';
comment on column spas_exam.status is '0 processing 1 done 2 failed';
comment on column spas_exam.dept_id is 'class used for name matching';

create table spas_exam_score (
  score_id int8 generated by default as identity not null,
  exam_id int8 not null,
  student_id int8 not null,
  score_type varchar(1) not null,
  subject_name varchar(64),
  score numeric(10,2),
  school_rank int4,
  create_time timestamp,
  update_time timestamp,
  primary key (score_id)
);

create unique index uk_spas_exam_score
  on spas_exam_score (exam_id, student_id, score_type, (coalesce(subject_name, '')));

create index idx_spas_exam_score_exam on spas_exam_score(exam_id);
create index idx_spas_exam_score_student on spas_exam_score(student_id);

comment on table spas_exam_score is 'student subject or total score with school rank; subject_name from Excel header';
comment on column spas_exam_score.score_type is '1 subject 2 total';
comment on column spas_exam_score.subject_name is 'subject label from Excel; null when score_type=2';
comment on column spas_exam_score.school_rank is 'school-wide rank';
