-- P2-11: intervene knowledge join table (dual-write with knowledge_ids CSV)
-- Apply: python sql/spas_apply_incremental.py  OR  psql -f sql/spas_intervene_knowledge.sql

create table if not exists spas_intervene_knowledge (
  id int8 generated by default as identity not null,
  intervene_id int8 not null,
  knowledge_id int8 not null,
  create_time timestamp default now(),
  primary key (id),
  constraint uk_spas_intervene_knowledge unique (intervene_id, knowledge_id)
);
create index if not exists idx_spas_ik_intervene on spas_intervene_knowledge(intervene_id);
create index if not exists idx_spas_ik_knowledge on spas_intervene_knowledge(knowledge_id);
comment on table spas_intervene_knowledge is 'intervene task linked knowledge nodes (normalized)';

-- backfill from CSV knowledge_ids
insert into spas_intervene_knowledge(intervene_id, knowledge_id, create_time)
select t.intervene_id, cast(trim(x) as int8), coalesce(t.create_time, now())
from spas_intervene_task t
cross join lateral unnest(string_to_array(coalesce(t.knowledge_ids, ''), ',')) as x
where trim(x) ~ '^[0-9]+$'
  and not exists (
    select 1 from spas_intervene_knowledge ik
    where ik.intervene_id = t.intervene_id and ik.knowledge_id = cast(trim(x) as int8)
  );
