-- SPAS question bank (Plan B) ?? PostgreSQL idempotent

-- Tables: spas_qb_* ; alter spas_paper / spas_paper_question for bridge



-- ========== questions ==========

create table if not exists spas_qb_question (

  question_id int8 generated by default as identity not null,

  question_code varchar(32),

  content text not null,

  options text,

  correct_answer text,

  subject_id int8 not null,

  question_type varchar(32) default 'short',

  difficulty char(1) default '2',

  analysis text,

  content_hash varchar(64),

  status char(1) default '0',

  del_flag char(1) default '0',

  create_by varchar(64) default '',

  create_time timestamp,

  update_by varchar(64) default '',

  update_time timestamp,

  remark varchar(500),

  stem_image varchar(500),

  options_image varchar(500),

  answer_image varchar(500),

  analysis_image varchar(500),

  primary key (question_id)

);

create index if not exists idx_spas_qb_q_subject on spas_qb_question(subject_id, del_flag);

create unique index if not exists uk_spas_qb_q_hash_subject

  on spas_qb_question(subject_id, content_hash) where content_hash is not null and del_flag = '0';

comment on table spas_qb_question is 'SPAS question bank item with stem';

comment on column spas_qb_question.difficulty is '1 easy 2 medium 3 hard';

comment on column spas_qb_question.status is '0 draft 1 published';



-- ========== bank knowledge (reviewed) ==========

create table if not exists spas_qb_question_knowledge (

  id int8 generated by default as identity not null,

  question_id int8 not null,

  knowledge_id int8 not null,

  weight numeric(8,4) default 1,

  is_primary char(1) default '0',

  primary key (id),

  constraint uk_spas_qb_qk unique (question_id, knowledge_id)

);

create index if not exists idx_spas_qb_qk_kid on spas_qb_question_knowledge(knowledge_id);



-- ========== bank paper ==========

create table if not exists spas_qb_paper (

  paper_id int8 generated by default as identity not null,

  paper_title varchar(200) not null,

  subject_id int8 not null,

  total_score numeric(8,2) default 0,

  status char(1) default '0',

  create_by varchar(64) default '',

  create_time timestamp,

  update_by varchar(64) default '',

  update_time timestamp,

  remark varchar(500),

  primary key (paper_id)

);

comment on column spas_qb_paper.status is '0 draft 1 ready';



create table if not exists spas_qb_paper_item (

  item_id int8 generated by default as identity not null,

  paper_id int8 not null,

  question_id int8 not null,

  order_num int4 not null default 0,

  score_value numeric(8,2) not null default 5,

  question_no varchar(32),

  primary key (item_id)

);

create index if not exists idx_spas_qb_item_paper on spas_qb_paper_item(paper_id, order_num);



-- ========== AI suggest log (optional) ==========

create table if not exists spas_qb_ai_suggest_log (

  log_id int8 generated by default as identity not null,

  question_id int8 not null,

  request_json text,

  response_json text,

  adopted char(1) default '0',

  create_by varchar(64) default '',

  create_time timestamp,

  primary key (log_id)

);



-- ========== bridge columns ==========

alter table spas_paper add column if not exists bank_paper_id int8;

create index if not exists idx_spas_paper_bank on spas_paper(bank_paper_id);



alter table spas_paper_question add column if not exists bank_question_id int8;

create index if not exists idx_spas_pq_bank on spas_paper_question(bank_question_id);



-- ========== visual annotate (also in spas_qb_annotate.sql for existing DBs) ==========

alter table spas_qb_question add column if not exists stem_image varchar(500);

alter table spas_qb_question add column if not exists options_image varchar(500);

alter table spas_qb_question add column if not exists answer_image varchar(500);

alter table spas_qb_question add column if not exists analysis_image varchar(500);

create table if not exists spas_qb_annotate_session (

  session_id varchar(64) not null,

  subject_id int8 not null,

  file_name varchar(255),

  file_path varchar(500),

  page_count int4 default 0,

  status char(1) default '0',

  create_by varchar(64) default '',

  create_time timestamp,

  primary key (session_id)

);

create index if not exists idx_spas_qb_ann_subject on spas_qb_annotate_session(subject_id, create_time);

