-- P2-12: quality center work-order (ticket) table + menus
-- Apply: python sql/spas_apply_incremental.py  OR  psql -f sql/spas_quality_ticket.sql

create table if not exists spas_quality_ticket (
  ticket_id int8 generated by default as identity not null,
  metric_code varchar(64) not null,
  title varchar(200) not null,
  status char(1) default '0',
  priority char(1) default '2',
  dept_id int8,
  subject_id int8,
  ref_json text,
  owner_by varchar(64) default '',
  create_by varchar(64) default '',
  create_time timestamp,
  update_by varchar(64) default '',
  update_time timestamp,
  remark varchar(500),
  primary key (ticket_id)
);
create index if not exists idx_spas_qt_status on spas_quality_ticket(status, metric_code);
create index if not exists idx_spas_qt_dept on spas_quality_ticket(dept_id);
comment on table spas_quality_ticket is 'data quality work order';
comment on column spas_quality_ticket.status is '0=open 1=processing 2=done 3=closed';
comment on column spas_quality_ticket.priority is '1=high 2=mid 3=low';

insert into sys_dict_type(dict_name, dict_type, status, create_by, create_time, remark)
select 'Quality ticket status', 'spas_quality_ticket_status', '0', 'admin', now(), null
where not exists (select 1 from sys_dict_type where dict_type='spas_quality_ticket_status');

insert into sys_dict_type(dict_name, dict_type, status, create_by, create_time, remark)
select 'Quality ticket priority', 'spas_quality_ticket_priority', '0', 'admin', now(), null
where not exists (select 1 from sys_dict_type where dict_type='spas_quality_ticket_priority');

insert into sys_dict_data(dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time)
select * from (values
 (1, 'Open', '0', 'spas_quality_ticket_status', '', 'warning', 'Y', '0', 'admin', now()),
 (2, 'Processing', '1', 'spas_quality_ticket_status', '', 'primary', 'N', '0', 'admin', now()),
 (3, 'Done', '2', 'spas_quality_ticket_status', '', 'success', 'N', '0', 'admin', now()),
 (4, 'Closed', '3', 'spas_quality_ticket_status', '', 'info', 'N', '0', 'admin', now())
) as v(dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time)
where not exists (select 1 from sys_dict_data d where d.dict_type='spas_quality_ticket_status' and d.dict_value=v.dict_value);

insert into sys_dict_data(dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time)
select * from (values
 (1, 'High', '1', 'spas_quality_ticket_priority', '', 'danger', 'N', '0', 'admin', now()),
 (2, 'Mid', '2', 'spas_quality_ticket_priority', '', 'warning', 'Y', '0', 'admin', now()),
 (3, 'Low', '3', 'spas_quality_ticket_priority', '', 'info', 'N', '0', 'admin', now())
) as v(dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time)
where not exists (select 1 from sys_dict_data d where d.dict_type='spas_quality_ticket_priority' and d.dict_value=v.dict_value);

-- button perms under quality menu 2134
insert into sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time)
select 2136, 'Ticket query', 2134, 2, '', '', '', '', 1, 0, 'F', '0', '0', 'spas:quality:ticket:list', '#', 'admin', now()
where not exists (select 1 from sys_menu where menu_id=2136);

insert into sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time)
select 2137, 'Ticket add', 2134, 3, '', '', '', '', 1, 0, 'F', '0', '0', 'spas:quality:ticket:add', '#', 'admin', now()
where not exists (select 1 from sys_menu where menu_id=2137);

insert into sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time)
select 2138, 'Ticket edit', 2134, 4, '', '', '', '', 1, 0, 'F', '0', '0', 'spas:quality:ticket:edit', '#', 'admin', now()
where not exists (select 1 from sys_menu where menu_id=2138);

insert into sys_menu(menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time)
select 2139, 'Ticket remove', 2134, 5, '', '', '', '', 1, 0, 'F', '0', '0', 'spas:quality:ticket:remove', '#', 'admin', now()
where not exists (select 1 from sys_menu where menu_id=2139);

insert into sys_role_menu(role_id, menu_id)
select r.role_id, m.menu_id
from sys_role r
cross join (values (2136),(2137),(2138),(2139)) as m(menu_id)
where r.role_key in ('admin', 'spas_admin', 'spas_jw', 'spas_teacher', 'spas_bzr', 'spas_grade_leader', 'spas_school_leader')
  and not exists (
    select 1 from sys_role_menu rm where rm.role_id = r.role_id and rm.menu_id = m.menu_id
  );
